name: Deploy GitHub Pages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

# Permissões necessárias para publicar no GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite que apenas um deploy ocorra por vez
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job 1: Prepara os arquivos
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configura o GitHub Pages
        uses: actions/configure-pages@v5

      - name: Faz o upload da pasta src
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'src/' # Garante que o Pages leia o index.html daqui

  # Job 2: Publica o site
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publica no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4